# Generated by Django 6.0.4 on 2026-04-29 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='invoices/')),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, help_text='PIB / VAT number', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('line_items', models.JSONField(default=list, help_text='List of {description, quantity, unit_price}')),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('xml_output', models.TextField(blank=True, help_text='XML compliant with e‑invoicing (e.g., PEPPOL BIS)')),
                ('csv_output', models.TextField(blank=True, help_text='CSV version')),
                ('raw_ai_response', models.TextField(blank=True, help_text='Raw JSON from AI')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
