# Generated by Django 6.0.4 on 2026-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedinvoice',
            old_name='total_amount',
            new_name='amount_due',
        ),
        migrations.RenameField(
            model_name='processedinvoice',
            old_name='date',
            new_name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='processedinvoice',
            name='line_items',
        ),
        migrations.RemoveField(
            model_name='processedinvoice',
            name='total_tax',
        ),
        migrations.RemoveField(
            model_name='processedinvoice',
            name='vat_number',
        ),
        migrations.AddField(
            model_name='processedinvoice',
            name='extracted_data',
            field=models.JSONField(default=dict, help_text='Complete extracted data from AI'),
        ),
        migrations.AddField(
            model_name='processedinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='processedinvoice',
            name='language_detected',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='processedinvoice',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='processedinvoice',
            name='csv_output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processedinvoice',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='processedinvoice',
            name='raw_ai_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processedinvoice',
            name='vendor_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='processedinvoice',
            name='xml_output',
            field=models.TextField(blank=True),
        ),
    ]
