# Generated by Django 5.0.6 on 2026-04-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_total_amount_processedinvoice_amount_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedinvoice',
            name='payment_status',
            field=models.CharField(blank=True, default='Not Paid', max_length=50, null=True),
        ),
    ]
