# Generated by Django 5.0.6 on 2026-04-29 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_processedinvoice_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedinvoice',
            options={},
        ),
        migrations.AddField(
            model_name='processedinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processedinvoice',
            name='raw_ai_response',
            field=models.TextField(blank=True, help_text='Full raw text from Gemini'),
        ),
    ]
